// Mock data for trending products
export const productsData = [
  {
    id: 1,
    name: 'Apple iPhone 16 256 GB Ultramarine',
    price: '₦1,300,000',
    oldPrice: '₦1,400,000',
    discount: '-10%',
    condition: 'New',
    brand: 'kenwood',
    image: '/imgs/iphone.svg',
    images: [
      '/imgs/iphone.svg',
      '/imgs/gadgets.svg',
      '/imgs/power-bank.svg'
    ],
    location: 'Lagos, Nigeria',
    rating: 1,
    reviews: 1,
    verified: true,
    category: 'Gadgets',
  },
  {
    id: 2,
    name: 'LG Thick Table Top Glass Gas Cooker with Two Hobs',
    price: '₦34,000',
    image: '/imgs/gas-cooker.svg', 
    images: [
      '/imgs/gas-cooker.svg',
      '/imgs/blender.svg',
      '/imgs/yam-pounder.svg'
    ],
    location: 'Oyo, Nigeria',
    rating: 2,
    reviews: 0,
    verified: false,
    category: 'Electronics',
  },
  {
    id: 3,
    name: 'New Age 50000 MAh FC50P POWER BANK FAST CHARGE',
    price: '₦58,500',
    oldPrice: '₦1,400,000',
    discount: '-10%',
    image: '/imgs/power-bank.svg', 
    images: [
      '/imgs/power-bank.svg',
      '/imgs/gadgets.svg',
      '/imgs/iphone.svg'
    ],
    location: 'Lagos, Nigeria',
    brand: 'New Age',
    rating: 5,
    reviews: 100,
    verified: true,
    category: 'Electronics',
  },
  {
    id: 4,
    name: 'Yam Pounder - 8L - 2500w',
    price: '₦1,000,000',
    oldPrice: '₦1,600,000',
    discount: '-30%',
    condition: 'used',
    brand: 'Pinnacle',
    image: '/imgs/yam-pounder.svg',
    images: [
      '/imgs/yam-pounder.svg',
      '/imgs/blender.svg',
      '/imgs/gas-cooker.svg'
    ],
    location: 'Lagos, Nigeria',
    rating: 1,
    reviews: 1,
    verified: false,
    category: 'Home and Kitchen',
  },
  {
    id: 5,
    name: 'Lexus 2021 RX350 White',
    price: '₦14, 000,000',
    oldPrice: '₦24,000,000',
    discount: '-10%',
    condition: 'New',
    brand: 'Lexus',
    image: '/imgs/lexus.svg',
    images: [
      '/imgs/lexus.svg',
      '/imgs/vehicles.svg',
      '/imgs/vehicle-sales.svg'
    ],
    location: 'Lagos, Nigeria',
    rating: 5,
    reviews: 1,
    verified: false,
    category: 'Vehicles',
  },
  {
    id: 6,
    name: 'LG Thick Table Top Glass Gas Cooker with Two Hobs',
    price: '₦34,000',
    image: '/imgs/blender.svg', 
    location: 'Oyo, Nigeria',
    rating: 2,
    reviews: 0,
    verified: false,
    category: 'Home and Kitchen',
  },
  {
    id: 7,
    name: 'New Age 50000 MAh FC50P POWER BANK FAST CHARGE',
    price: '₦58,500',
    image: '/imgs/gadgets.svg',  
    location: 'Lagos, Nigeria',
    rating: 5,
    reviews: 100,
    verified: true,
    category: 'Electronics',
  },
  {
    id: 8,
    name: 'Yam Pounder - 8L - 2500w',
    price: '₦1,4,000,000',
    image: '/imgs/blender.svg', 
    location: 'Lagos, Nigeria',
    rating: 1,
    reviews: 1,
    verified: false,
    category: 'Home and Kitchen',

  },
  {id: 9,
    name: 'Venza 2021',
    price: '₦14, 000,000',
    condition: 'used',
    brand: 'Lexus',
    image: '/imgs/lexus.svg',
    location: 'Lagos, Nigeria',
    rating: 3,
    reviews: 1,
    verified: true,
    category: 'Vehicles',
  },
];