// Mock data for trending products
export const productsData = [
  {
    id: 1,
    name: 'Apple iPhone 16 256 GB Ultramarine',
    price: '₦1,300,000',
    oldPrice: '₦1,400,000',
    discount: '-10%',
    condition: 'New',
    brand: 'kenwood',
    image: '/imgs/iphone.svg',
    images: [
      '/imgs/iphone.svg',
      '/imgs/gadgets.svg',
      '/imgs/power-bank.svg'
    ],
    location: 'Lagos, Nigeria',
    rating: 1,
    reviews: 1,
    verified: true,
    category: 'Gadgets',
    stock: 25,
    date: '04/17/2025',
    status: 'In Stock'
  },
  {
    id: 2,
    name: 'LG Thick Table Top Glass Gas Cooker with Two Hobs',
    price: '₦34,000',
    image: '/imgs/gas-cooker.svg', 
    images: [
      '/imgs/gas-cooker.svg',
      '/imgs/blender.svg',
      '/imgs/yam-pounder.svg'
    ],
    location: 'Oyo, Nigeria',
    rating: 2,
    reviews: 0,
    verified: false,
    category: 'Electronics',
    stock: 0,
    date: '04/15/2025',
    status: 'Out of Stock'
  },
  {
    id: 3,
    name: 'New Age 50000 MAh FC50P POWER BANK FAST CHARGE',
    price: '₦58,500',
    oldPrice: '₦1,400,000',
    discount: '-10%',
    image: '/imgs/power-bank.svg', 
    images: [
      '/imgs/power-bank.svg',
      '/imgs/gadgets.svg',
      '/imgs/iphone.svg'
    ],
    location: 'Lagos, Nigeria',
    brand: 'New Age',
    rating: 5,
    reviews: 100,
    verified: true,
    category: 'Electronics',
    stock: 50,
    date: '04/16/2025',
    status: 'In Stock'
  },
  {
    id: 4,
    name: 'Kenwood Yam Pounder - 8L - 2500w',
    price: '₦20,000',
    oldPrice: '₦25,000',
    discount: '-20%',
    condition: 'New',
    brand: 'Kenwood',
    image: '/imgs/yam-pounder.svg',
    images: [
      '/imgs/yam-pounder.svg',
      '/imgs/blender.svg',
      '/imgs/gas-cooker.svg'
    ],
    location: 'Lagos, Nigeria',
    rating: 4,
    reviews: 15,
    verified: true,
    category: 'Home and Kitchen',
    stock: 40,
    date: '04/17/2025',
    status: 'In Stock'
  },
  {
    id: 5,
    name: 'Lexus 2021 RX350 White',
    price: '₦14,000,000',
    oldPrice: '₦24,000,000',
    discount: '-42%',
    condition: 'Used',
    brand: 'Lexus',
    image: '/imgs/lexus.svg',
    images: [
      '/imgs/lexus.svg',
      '/imgs/vehicles.svg',
      '/imgs/vehicle-sales.svg'
    ],
    location: 'Lagos, Nigeria',
    rating: 5,
    reviews: 1,
    verified: false,
    category: 'Vehicles',
    stock: 1,
    date: '04/10/2025',
    status: 'In Stock'
  },
  {
    id: 6,
    name: 'Kenwood Yam Pounder',
    price: '₦20,000',
    image: '/imgs/yam-pounder.svg', 
    location: 'Oyo, Nigeria',
    rating: 4,
    reviews: 8,
    verified: true,
    category: 'Home and Kitchen',
    stock: 30,
    date: '04/17/2025',
    status: 'In Stock'
  },
  {
    id: 7,
    name: 'Kenwood Yam Pounder',
    price: '₦20,000',
    image: '/imgs/yam-pounder.svg',  
    location: 'Lagos, Nigeria',
    rating: 5,
    reviews: 22,
    verified: true,
    category: 'Home and Kitchen',
    stock: 0,
    date: '04/12/2025',
    status: 'Out of Stock'
  },
  {
    id: 8,
    name: 'Kenwood Yam Pounder',
    price: '₦20,000',
    image: '/imgs/yam-pounder.svg', 
    location: 'Lagos, Nigeria',
    rating: 4,
    reviews: 12,
    verified: false,
    category: 'Home and Kitchen',
    stock: 35,
    date: '04/17/2025',
    status: 'In Stock'
  },
  {
    id: 9,
    name: 'Kenwood Yam Pounder',
    price: '₦20,000',
    condition: 'New',
    brand: 'Kenwood',
    image: '/imgs/yam-pounder.svg',
    location: 'Lagos, Nigeria',
    rating: 4,
    reviews: 18,
    verified: true,
    category: 'Home and Kitchen',
    stock: 45,
    date: '04/17/2025',
    status: 'In Stock'
  },
  {
    id: 10,
    name: 'Kenwood Yam Pounder',
    price: '₦20,000',
    image: '/imgs/yam-pounder.svg',
    location: 'Lagos, Nigeria',
    rating: 3,
    reviews: 5,
    verified: true,
    category: 'Home and Kitchen',
    stock: 20,
    date: '04/16/2025',
    status: 'In Stock'
  },
  {
    id: 11,
    name: 'Kenwood Yam Pounder',
    price: '₦20,000',
    image: '/imgs/yam-pounder.svg',
    location: 'Lagos, Nigeria',
    rating: 5,
    reviews: 30,
    verified: true,
    category: 'Home and Kitchen',
    stock: 15,
    date: '04/17/2025',
    status: 'In Stock'
  },
  {
    id: 12,
    name: 'Kenwood Yam Pounder',
    price: '₦20,000',
    image: '/imgs/yam-pounder.svg',
    location: 'Lagos, Nigeria',
    rating: 4,
    reviews: 25,
    verified: false,
    category: 'Home and Kitchen',
    stock: 0,
    date: '04/14/2025',
    status: 'Out of Stock'
  },
  {
    id: 13,
    name: 'Kenwood Yam Pounder',
    price: '₦20,000',
    image: '/imgs/yam-pounder.svg',
    location: 'Lagos, Nigeria',
    rating: 4,
    reviews: 10,
    verified: true,
    category: 'Home and Kitchen',
    stock: 28,
    date: '04/17/2025',
    status: 'In Stock'
  },
  {
    id: 14,
    name: 'Kenwood Yam Pounder',
    price: '₦20,000',
    image: '/imgs/yam-pounder.svg',
    location: 'Lagos, Nigeria',
    rating: 5,
    reviews: 40,
    verified: true,
    category: 'Home and Kitchen',
    stock: 55,
    date: '04/17/2025',
    status: 'In Stock'
  },
  {
    id: 15,
    name: 'Kenwood Yam Pounder',
    price: '₦20,000',
    image: '/imgs/yam-pounder.svg',
    location: 'Lagos, Nigeria',
    rating: 4,
    reviews: 8,
    verified: true,
    category: 'Home and Kitchen',
    stock: 0,
    date: '04/13/2025',
    status: 'Out of Stock'
  }
];